[package]
name = "app"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
cores.workspace = true
lazuli.workspace = true
modules.workspace = true
renderer.workspace = true
vtxjit.workspace = true

bytesize.workspace = true
clap.workspace = true
eyre-pretty.workspace = true
indexmap.workspace = true
nanorand.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true

directories = "6"
eframe = {
  version = "0.36",
  default-features = false,
  features = [
    # platforms
    "wayland",
    "x11",

    # renderer backend
    "wgpu",

    "default_fonts",
    # eframe features
    "persistence",
  ]
}
egui_extras = { version = "0.36" }
image = { version = "0.25", default-features = false, features = ["png"] }
ron = { version = "0.11" }
spin_sleep = "1.3"
tracing-appender = "0.2"
typetag = "0.2"

[target.'cfg(not(target_os = "macos"))'.dependencies]
renderdoc = "0.12"

[lints]
workspace = true
